//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AltKategoriler
    {
        public int AltKategoriId { get; set; }
        public string AltKategoriAdi { get; set; }
        public string Resim { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<bool> Sil { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public string Url { get; set; }
        public Nullable<int> SiraNo { get; set; }
    }
}
