//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvanterServerler
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public string Barkod { get; set; }
        public string ServerModeli { get; set; }
        public string Cpu { get; set; }
        public string Ram { get; set; }
        public string SistemDiski { get; set; }
        public string ServerAdi { get; set; }
        public string ServerSifresi { get; set; }
        public string FirmaIPPort { get; set; }
        public string ServerIP { get; set; }
        public string DomainServerId { get; set; }
        public string DomainServerSifresi { get; set; }
        public string DomainAdi { get; set; }
        public string DomainServerIp { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
