//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnvanterBilgisayarlar
    {
        public int Id { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public string UrununTuru { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciMailAdresi { get; set; }
        public string Barkod { get; set; }
        public string Cpu { get; set; }
        public string Ram { get; set; }
        public string SistemDiski { get; set; }
        public string EkranKarti { get; set; }
        public string IsletimSistemi { get; set; }
        public string KullandigiDigerYazilimlar1 { get; set; }
        public string KullandigiDigerYazilimlar2 { get; set; }
        public string KullandigiDigerYazilimlar3 { get; set; }
        public string OfficeSurumu { get; set; }
        public string Antivirus { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
