//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int Id { get; set; }
        public string SirketAdi { get; set; }
        public string YetkiliKisi { get; set; }
        public string EPosta { get; set; }
        public string Sifre { get; set; }
        public string TelefonNo1 { get; set; }
        public string TelefonNo2 { get; set; }
        public string CepTelefonu { get; set; }
        public string FaxNo { get; set; }
        public string Ulke { get; set; }
        public string Il { get; set; }
        public string Ilce { get; set; }
        public string Semt { get; set; }
        public string Adres { get; set; }
        public string VergiDairesi { get; set; }
        public string VergiNo { get; set; }
        public string MusteriGrubu { get; set; }
        public string MusteriAnaGrubu { get; set; }
        public string MusteriAltGrubu { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Arama { get; set; }
        public Nullable<int> PcAdet { get; set; }
        public string Sektorler { get; set; }
        public Nullable<System.DateTime> SonIslemTarihi { get; set; }
        public string PazarlamaDurumu { get; set; }
    }
}
