//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string KullaniciAdi { get; set; }
        public string Email { get; set; }
        public string Sifresi { get; set; }
        public Nullable<byte> Yetki { get; set; }
        public string Gorev { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string MedeniDurumu { get; set; }
        public string TCKimlikNo { get; set; }
        public string KisiselTelefonu { get; set; }
        public string SirketTelefonu { get; set; }
        public Nullable<System.DateTime> IseGirisTarihi { get; set; }
        public string Aciklama { get; set; }
        public string SiteTemasi { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Resim { get; set; }
        public Nullable<bool> Aktif { get; set; }
    }
}
