//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restorant_users
    {
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string smscode { get; set; }
        public string customer_name { get; set; }
        public string customer_surname { get; set; }
        public string customer_id { get; set; }
        public Nullable<bool> isLocked { get; set; }
        public Nullable<System.DateTime> lockDate { get; set; }
        public Nullable<decimal> last_balance { get; set; }
        public Nullable<int> wrongLoginCount { get; set; }
    }
}
