//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class restorant_activity
    {
        public int id { get; set; }
        public string restaurant_name { get; set; }
        public Nullable<System.DateTime> process_date { get; set; }
        public string process_type { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string pos_or_mobile { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> restaurant_id { get; set; }
    }
}
