//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YesisCRMWS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Restaurants
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string description { get; set; }
        public string Address { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string category { get; set; }
        public string logourl { get; set; }
        public string town { get; set; }
        public Nullable<double> distance { get; set; }
    }
}
